# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://teamvectron.com
title: Vectron RO034
email: teamvectron@gmail.com
author: Vectron
description: > # "Write an awesome description for your new site here. 
  We are a robotics team from Dej, Cluj, Romania. We participate in the First Tech Challenge competition.
copyright: 'Copyright &copy; 2019 Vectron. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://facebook.com/teamvectron
  - title: instagram
    url: https://www.instagram.com/teamvectron/
  - title: youtube
    url: https://www.youtube.com/channel/UCbzFYmYaNJbCe9-4A2g-FNw
  - title: github
    url: https://github.com/vectronromania
